"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_env_file(path):
    if not path.exists():
        return

    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue

        key, value = line.split("=", 1)
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


load_env_file(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*pzc@mz!3tpn0962mku74ydli5=t!%7n2*n@b^w#*7%wuk9r+7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    "corsheaders",
    "api",
    "account",
    "news",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

CORS_ALLOW_CREDENTIALS = True

SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Дополнительные настройки для аватаров
DATA_UPLOAD_MAX_NUMBER_FILES = 10
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10240

# Email settings for appeal notifications
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.smtp.EmailBackend",
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.yandex.ru")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "465"))
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "true").lower() == "true"
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "false").lower() == "true"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)
APPEAL_RECIPIENT_EMAILS = [
    email.strip()
    for email in os.getenv(
        "APPEAL_RECIPIENT_EMAILS",
        "HostelHelperTiu@yandex.ru,hostelhelpertiu@gmail.com",
    ).split(",")
    if email.strip()
]
APPEAL_EMAIL_SENDERS = [
    {
        "host": EMAIL_HOST,
        "port": EMAIL_PORT,
        "username": EMAIL_HOST_USER,
        "password": EMAIL_HOST_PASSWORD,
        "use_ssl": EMAIL_USE_SSL,
        "use_tls": EMAIL_USE_TLS,
        "from_email": DEFAULT_FROM_EMAIL,
    },
    {
        "host": os.getenv("GMAIL_EMAIL_HOST", "smtp.gmail.com"),
        "port": int(os.getenv("GMAIL_EMAIL_PORT", "587")),
        "username": os.getenv("GMAIL_EMAIL_HOST_USER", ""),
        "password": os.getenv("GMAIL_EMAIL_HOST_PASSWORD", ""),
        "use_ssl": os.getenv("GMAIL_EMAIL_USE_SSL", "false").lower() == "true",
        "use_tls": os.getenv("GMAIL_EMAIL_USE_TLS", "true").lower() == "true",
        "from_email": os.getenv(
            "GMAIL_DEFAULT_FROM_EMAIL",
            os.getenv("GMAIL_EMAIL_HOST_USER", ""),
        ),
    },
]

# Gmail settings for password reset (использует переменные из .env)
GMAIL_EMAIL_HOST = os.getenv("GMAIL_EMAIL_HOST", "smtp.gmail.com")
GMAIL_EMAIL_PORT = int(os.getenv("GMAIL_EMAIL_PORT", "587"))
GMAIL_EMAIL_USE_SSL = os.getenv("GMAIL_EMAIL_USE_SSL", "false").lower() == "true"
GMAIL_EMAIL_USE_TLS = os.getenv("GMAIL_EMAIL_USE_TLS", "true").lower() == "true"
GMAIL_EMAIL_HOST_USER = os.getenv("GMAIL_EMAIL_HOST_USER", "")
GMAIL_EMAIL_HOST_PASSWORD = os.getenv("GMAIL_EMAIL_HOST_PASSWORD", "").replace(" ", "")
GMAIL_DEFAULT_FROM_EMAIL = os.getenv("GMAIL_DEFAULT_FROM_EMAIL", GMAIL_EMAIL_HOST_USER)

FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:5173")
BACKEND_PUBLIC_URL = os.getenv("BACKEND_PUBLIC_URL", "http://localhost:8000").rstrip("/")

# VK news notifications
VK_NEWS_BOT_ENABLED = os.getenv("VK_NEWS_BOT_ENABLED", "false").lower() == "true"
VK_BOT_TOKEN = os.getenv("VK_BOT_TOKEN", "")
VK_NEWS_PEER_ID = os.getenv("VK_NEWS_PEER_ID", "")
VK_API_VERSION = os.getenv("VK_API_VERSION", "5.199")
VK_NEWS_SEND_TIMEOUT = float(os.getenv("VK_NEWS_SEND_TIMEOUT", "5"))
VK_NEWS_MESSAGE_PREFIX = os.getenv("VK_NEWS_MESSAGE_PREFIX", "Новая новость")
NEWS_PUBLIC_URL = os.getenv("NEWS_PUBLIC_URL", f"{FRONTEND_URL.rstrip('/')}/home")

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
