# Generated by Django 6.0.5 on 2026-05-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_patronymic_to_middle_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hostel',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Номер общежития'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=11, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='university',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Институт'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='has_no_middle_name',
            field=models.BooleanField(default=False, verbose_name='Нет отчества'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='room_number',
            field=models.CharField(max_length=20, verbose_name='Номер комнаты'),
        ),
    ]
