# Generated by Django 6.0.5 on 2026-06-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_userprofile_options_userprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='balance_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Переплата'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='balance_debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Задолженность'),
        ),
    ]
