# Generated by Codex on 2026-05-18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsPost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=160, verbose_name="Заголовок")),
                ("summary", models.CharField(max_length=280, verbose_name="Краткое описание")),
                ("content", models.TextField(blank=True, verbose_name="Текст новости")),
                ("image", models.ImageField(blank=True, null=True, upload_to="news/", verbose_name="Изображение")),
                ("is_published", models.BooleanField(default=True, verbose_name="Опубликовано")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата публикации")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
            ],
            options={
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
                "ordering": ["-created_at"],
            },
        ),
    ]
